const $=s=>document.querySelector(s);
const music=$('#music'), toggle=$('#music-toggle');
function musicState(){toggle.textContent=music.paused?'♫':'Ⅱ';toggle.setAttribute('aria-label',music.paused?'Reproducir música':'Pausar música');toggle.setAttribute('aria-pressed',String(!music.paused));}
music.addEventListener('play',musicState);music.addEventListener('pause',musicState);
toggle.addEventListener('click',()=>{if(music.paused)music.play().catch(musicState);else music.pause();});
$('#open').addEventListener('click',()=>{music.play().catch(musicState);$('#welcome').classList.add('leaving');$('#open').disabled=true;setTimeout(()=>{$('#welcome').hidden=true;$('#invitation').hidden=false;toggle.hidden=false;document.body.classList.add('opening');window.scrollTo(0,0);$('h1').focus({preventScroll:true});document.querySelectorAll('.reveal').forEach(s=>{s.classList.add('ready');observer.observe(s);});},650);});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.07});
const gallery=[['juntos.webp','Jhonatan y Rouss juntos en el jardín'],['puente.webp','Un abrazo sobre el puente'],['abrazo.webp','Un instante de nuestra historia'],['brindis.webp','Brindando por nuestra vida juntos'],['beso.webp','Un beso lleno de amor'],['anillos.webp','Nuestro anillo y un brindis']];let active=0;
function photo(step=0){active=(active+step+gallery.length)%gallery.length;$('#album-photo').src=gallery[active][0];$('#album-photo').alt=gallery[active][1];$('#photo-count').textContent=`${String(active+1).padStart(2,'0')} / 06`;$('#large-photo').src=gallery[active][0];$('#large-photo').alt=gallery[active][1];$('#large-count').textContent=`${active+1} / 6`;}
$('#previous').onclick=()=>photo(-1);$('#next').onclick=()=>photo(1);$('#large-previous').onclick=()=>photo(-1);$('#large-next').onclick=()=>photo(1);
const box=$('#lightbox');$('#album-open').onclick=()=>{photo();box.showModal();};$('.close').onclick=()=>box.close();box.addEventListener('click',e=>{if(e.target===box)box.close();});box.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')photo(-1);if(e.key==='ArrowRight')photo(1);});let touchX=0;$('#album-photo').addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});$('#album-photo').addEventListener('touchend',e=>{let diff=e.changedTouches[0].clientX-touchX;if(Math.abs(diff)>45){photo(diff<0?1:-1);e.preventDefault();}},{passive:false});
for(let d=-2;d<=31;d++){const s=document.createElement('span');if(d>0)s.textContent=d;if(d===17){s.className='chosen';s.setAttribute('aria-label','17 de octubre, nuestra boda');}$('#calendar').append(s);}
function count(){let n=Math.max(0,new Date('2026-10-17T16:00:00-04:00')-Date.now());['days','hours','minutes','seconds'].forEach((id,i)=>{const unit=[86400000,3600000,60000,1000][i];$('#'+id).textContent=String(Math.floor(n/unit)).padStart(2,'0');n%=unit;});}count();setInterval(count,1000);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');for(let i=0;i<40;i++){const p=document.createElement('i');p.style.cssText=`--left:${Math.random()*100}%;--size:${9+Math.random()*11}px;--duration:${11+Math.random()*13}s;--delay:-${Math.random()*25}s;--drift:${-100+Math.random()*200}px;--spin:${180+Math.random()*600}deg`;$('#petals').append(p);}let petalsOn=!reduced.matches;function petalState(){$('#petals').classList.toggle('paused',!petalsOn);$('#petal-toggle').setAttribute('aria-pressed',String(petalsOn));$('#petal-toggle').setAttribute('aria-label',petalsOn?'Pausar pétalos':'Activar pétalos');}petalState();$('#petal-toggle').onclick=()=>{petalsOn=!petalsOn;petalState();};reduced.addEventListener('change',()=>{petalsOn=!reduced.matches;petalState();});document.addEventListener('visibilitychange',()=>$('#petals').classList.toggle('paused',document.hidden||!petalsOn));
